name: Build and release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5

      - name: Build
        run: cargo build --release --features usnrs-cli

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            target/release/usnrs-cli
            target/release/usnrs-cli.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          merge-multiple: true

      - name: Publish latest pre-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          prerelease: true
          files: |
            usnrs-cli
            usnrs-cli.exe
